#config_version=5
mode: 
  start_events: mode_rza_start
  stop_events: rza_completed #, rza_timer_complete
  priority: 1000
  
#  RZA
#  - to qualify- complete upper rollovers 3x, shoot saucer and select
#  - song: holocaust/silkworm (5:03)
#  - complete all 5 rollovers 3x, completions award 50k + 2k/pop

# todo- add scoring increases and completion award

accruals:
  rza_accrual:
    events:
      - right_rollover
      - center_rollover
      - Left_rolloverr
    reset_on_complete: false     
event_player:
  test_event{device.accruals.test_accrual.value[0]}: right_rollover
  test_event{device.accruals.test_accrual.value[1]}: center_rollover
  test_event{device.accruals.test_accrual.value[2]}: left_rollover
  test_event{device.accruals.test_accrual.completed}: accrual_completed


counters:
  rollover_counter:
    count_events: rza_accrual_completed
    count_complete_value: 3

variable_player:
  rza_accrual_completed:
    score: 50000
  rza_completed:
    score: 200000

sounds:
  holocaust:
    volume: 0.5
    priority: 100 

timers:
  rza_timer:
    start_value: 303
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true

slides:
  rzavideo:
    - type: video
      video: rzaedit2
      end_behavior: loop
