#config_version=5

mode:
  start_events: ball_starting
  priority: 100

ball_holds:
  mode_start:
    balls_to_hold: 1
    hold_devices: bd_left_saucer
    enable_events:
    disable_events: multiball_active
    #release_one_events: my_carousel_item_selected

slide_player:
  # Main display
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        color: green
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        color: green
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        color: green
        font_size: 50

variable_player:
  my_first_shot_my_first_profile_unlit_hit:
    score: 100
  my_first_shot_my_first_profile_flashing_hit:
    score: 1000
  s_bottom_popper_active:
    score: 100
  s_right_inlane_active:
    score: 10
  s_plumb_bob_active:
    score: 50
  s_left_outlane_active:
    score: 100
  s_left_inlane_active:
    score: 10
  s_standup_1_active:
    score: 40
  s_standup_2_active:
    score: 40
  s_standup_3_active:
    score: 40
  s_standup_4_active:
    score: 40
  s_standup_5_active:
    score: 40
  s_right_slingshot_active:
    score: 30
  s_left_slingshot_active:
    score: 30
  s_upper_slingshot_active:
    score: 30
  s_left_jet_bumper_active:
    score: 30
  s_right_jet_bumper_active:
    score: 30
#todo change ramp exit switch scoring to shot scoring
  s_right_ramp_exit_active:
    score: 100
  s_left_ramp_exit_active:
    score: 100
  s_side_ramp_exit_active:
    score: 100
  s_center_ramp_active:
    score: 100
  s_right_spinner_active:
    score: 10
  s_left_loop_active:
    score: 50
  s_right_rollover_active:
    score: 10
  s_center_rollover_active:
    score: 10
  s_left_rollover_active:
    score: 10
  s_chase_car_1_active:
    score: 20
  s_chase_car_2_active:
    score: 30
  s_chase_car_standup_active:
    score: 50
  s_upper_rebound_active:
    score: 10
  s_top_popper_active:
    score: 50
  s_lower_rebound_active:
    score: 10
  s_ring_ramp_active:
    score: 100
  s_left_saucer_active:
    score: 50
  s_right_loop_active:
    score: 50

shots:
  shot_right_ramp:
    hit_events: right_ramp_hit
  shot_left_ramp:
    hit_events: left_ramp_hit
  shot_side_ramp:
    hit_events: side_ramp_hit
  shot_right_orbit:
    switches: s_right_loop
  shot_center_ramp:
    switches: s_center_ramp
  shot_left_orbit:
    switches: s_left_loop
  shot_car_crash:
    switches: s_chase_car_1
  shot_bottom_scoop:
    switches: s_bottom_popper
  shot_captive_ball:
    switches: s_captive_ball_standup

shot_profiles:
  my_first_profile:
    states:
      - name: unlit  # step 1
        show: off
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: true

sequence_shots:
  right_ramp:
    switch_sequence: s_right_ramp_enter, s_right_ramp_exit
    sequence_timeout: 3s
  left_ramp:
    switch_sequence: s_left_ramp_enter, s_left_ramp_exit
    sequence_timeout: 3s
  side_ramp:
    switch_sequence: s_side_ramp_enter, s_side_ramp_exit
    sequence_timeout: 3s
  ring_ramp:
    switch_sequence: s_right_ramp_enter, s_ring_ramp
    sequence_timeout: 3s

sounds:
  ruckusbase:
    #file: ruckusbase.wav
    volume: 0.5
  reunitedbase:
    #file: reunitedbase.wav
    volume: 0.5
  shadowboxinbase:
    #file: shadowboxinbase.wav
    volume: 0.5
  tearzbase:
    #file: tearzbase.wav
    volume: 0.5
  triumphbase:
    #file: triumph.wav
    volume: 0.5

sound_pools:
  basemusic:
    type: random
    track: music
    priority: 100
    sounds:
      - ruckusbase
      - reunitedbase
      - shadowboxinbase
      - tearzbase
      - triumphbase

sound_player:
  mode_base_started:
    basemusic:
      priority: 100
      loops: -1
  tilt_warning: warningtearz
  tilt: tilttearz
  s_standup_1_active: coin
  s_standup_2_active: coin
  s_standup_3_active: coin
  s_standup_4_active: coin
  s_standup_5_active: coin
  s_left_slingshot_active: sword
  s_right_slingshop_active: sword
  s_right_spinner_active: spinner
  s_left_jet_bumper_active: scratch1
  s_right_jet_bumper_active: scratch2
  s_upper_slingshot_active: scratch3

playlists:
  playliststart:
    shuffle: true
    repeat: false
    sounds:
      - start1
      - start2
      - start3
      - upfromthe36

  


