#config_version=5
mode:
  start_events: balldevice_bd_left_saucer_ball_enter
  stop_events: my_carousel_item_selected
  code: mpf.modes.carousel.code.carousel.Carousel
  use_wait_queue: true
mode_settings:
  selectable_items: deck, ugod, method, odb, mastakilla, raekwon, ghostface, gza, rza, cappadonna, protect, simple, nuthin, gravel, triumph
  select_item_events: s_start_inactive
  next_item_events: s_right_flipper_inactive
  previous_item_events: s_left_flipper_inactive
slide_player:
  my_carousel_deck_highlighted: select_deck
  my_carousel_ugod_highlighted: select_ugod
  my_carousel_method_highlighted: select_method
  my_carousel_odb_highlighted: select_odb
  my_carousel_mastakilla_highlighted: select_mastakilla
  my_carousel_raekwon_highlighted: select_raekwon
  my_carousel_ghostface_highlighted: select_ghostface
  my_carousel_gza_highlighted: select_gza
  my_carousel_rza_highlighted: select_rza
  my_carousel_cappadonna_highlighted: select_cappadonna
  my_carousel_protect_highlighted: select_protect
  my_carousel_simple_highlighted: select_simple
  my_carousel_nuthin_highlighted: select_nuthin
  my_carousel_gravel_highlighted: select_gravel
  my_carousel_triumph_highlighted: select_triumph
slides:
  select_deck:
    widgets:
      - type: text
        text: INSPECTAH DECK
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_ugod:
    widgets:
      - type: text
        text: U-GOD
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_method:
    widgets:
      - type: text
        text: METHOD MAN
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_odb:
    widgets:
      - type: text
        text: OL DIRTY BASTARD
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_mastakilla:
    widgets:
      - type: text
        text: MASTA KILLA
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_raekwon:
    widgets:
      - type: text
        text: RAEKWON
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_ghostface:
    widgets:
      - type: text
        text: GHOSTFACE KILLAH
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_gza:
    widgets:
      - type: text
        text: GZA
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_rza:
    widgets:
      - type: text
        text: RZA
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_cappadonna:
    widgets:
      - type: text
        text: CAPPADONNA
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_protect:
    widgets:
      - type: text
        text: PROTECT YA NECK
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_simple:
    widgets:
      - type: text
        text: CAN IT BE THAT IT WAS ALL SO SIMPLE?
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_nuthin:
    widgets:
      - type: text
        text: WU-TANG CLAN AINT NUTHIN TO FUCK WIT
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_gravel:
    widgets:
      - type: text
        text: GRAVEL PIT
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
  select_triumph:
    widgets:
      - type: text
        text: TRIUMPH
        font_size: 100
        color: yellow
    transition:
      type: move_in
      direction: right
