#config_version=5

mode: 
  start_events: mode_ugod_start
  stop_events: u_god_completed #, ugod_timer_complete
  priority: 1000
  
#U-God
#  - to qualify- left orbit to upper scoop 3x, shoot saucer and select
#  - song: Bizarre (3:17)
#  - shoot 7 left orbit shots in time
#  - 1st orbit to scoop 20k
#  - pop bumpers increase upper scoop by 5k
#  - shoot right ramp with open diverter to complete
#  - completion bonus 5k x seconds remaining

# add score increases, diverter rules and completion bonus

#shots: left_orbit

counters:
  u_god_counter:
    persist_state: true
    count_events: left_orbit_hit
    starting_count: 7
    count_complete_value: 0
    direction: down
    events_when_complete: u_god_completed

variable_player:
  left_orbit_hit:
    score: 20000
  u_god_completed:
    score: 200000

sounds:
  bizarre:
    volume: 0.5
    priority: 100 

timers:
  ugod_timer:
    start_value: 197
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true

slides:
  ugodvideo:
    - type: video
      video: ugodedit2
      end_behavior: loop
