#config_version=5

mode: 
  start_events: mode_ghostface_start
  stop_events: ghostface_completed #, ghostface_timer_complete
  priority: 1000
  
  #Ghostface Killah
  # qualify- right ramp 3x to qualify, shoot saucer and select
  # Song: Cherchez La Ghost (2:25)
  # diverter open, each R ramp a countdown from 50k to 5k in 30s
  # make 5 right ramps, final ramp completes
  # completion bonus 5x remaining s
  
  #todo- add diverter rule and completion bonus

counters:
  right_ramp_counter:
    count_events: right_ramp_hit
    count_complete_value: 5

variable_player:
  right_ramp_hit:
    score: 50000
  ghostface_completed:
    score: 200000

sounds:
  cherchezlaghost:
    volume: 0.5
    priority: 100 

timers:
  ghostface_timer:
    start_value: 145
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true

slides:
  ghostface_video:
    - type: video
      video: ghostfaceedit2
      end_behavior: loop
      
widget_player:
  mode_ghostface_start: shoot_right_ramp
