#config_version=5

mode:
  start_events: ball_starting
  priority: 100

ball_holds:
  mode_start:
    balls_to_hold: 1
    hold_devices: bd_left_saucer
    enable_events: device.counters.deck_shots_counter.complete, device.counters.ugod_shots_counter.complete, device.counters.method_shots_counter.complete, device.counters.odb_shots_counter.complete, device.counters.mastakilla_shots_counter.complete, device.counters.raekwon_shots_counter.complete, device.counters.ghostface_shots_counter.complete, device.counters.gza_shots_counter.complete, device.counters.rza_shots_counter.complete, device.counter.cappadonna_shots_counter.complete
    disable_events: multiball_active
    release_one_events: my_carousel_item_selected

slide_player: 
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: 'POTATO VALUE: (potato)'
        y: 40%

variable_player:
  my_first_shot_my_first_profile_unlit_hit:
    score: 100
  my_first_shot_my_first_profile_flashing_hit:
    score: 1000
  s_left_flipper_active:
    score: 1000
    potato: 1
  s_right_flipper_active:
    potato: -2

shots:
  shot_right_ramp:
    hit_events: right_ramp_hit
  shot_left_ramp:
    hit_events: left_ramp_hit
  shot_side_ramp:
    hit_events: side_ramp_hit
  shot_right_orbit:
    switches: s_right_loop
  shot_center_ramp:
    switches: s_center_ramp
  shot_left_orbit:
    switches: s_left_loop
  shot_car_crash:
    switches: s_chase_car_1
  shot_bottom_scoop:
    switches: s_bottom_popper
  shot_captive_ ball:
    switches: s_captive_ball_standup

shot_profiles:
  my_first_profile:
    states:
      - name: unlit  # step 1
        show: off
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: true

sequence_shots:
  right_ramp:
    switch_sequence: s_right_ramp_enter, s_right_ramp_exit
    sequence_timeout: 3s
  left_ramp:
    switch_sequence: s_left_ramp_enter, s_left_ramp_exit
    sequence_timeout: 3s
  side_ramp:
    switch_sequence: s_side_ramp_enter, s_side_ramp_exit
    sequence_timeout: 3s
  ring_ramp:
    switch_sequence: s_right_ramp_enter, s_ring_ramp
    sequence_timeout: 3s




