#config_version=5
mode: 
  start_events: rza_selected
  stop_events: rza_completed

accruals:
  rza_accrual:
    events:
      - right_rollover
      - center_rollover
      - Left_rolloverr
    reset_on_complete: false     
event_player:
  test_event{device.accruals.test_accrual.value[0]}: right_rollover
  test_event{device.accruals.test_accrual.value[1]}: center_rollover
  test_event{device.accruals.test_accrual.value[2]}: left_rollover
  test_event{device.accruals.test_accrual.completed}: accrual_completed


counters:
  rollover_counter:
    count_events: rza_accrual_completed
    count_complete_value: 3

variable_player:
  rza_accrual_completed:
    score: 50000
  rza_completed:
    score: 200000

