#config_version=5
mode: 
  start_events: raekwon_selected
  stop_events: raekwon_completed
  priority: 1000


state_machines:
  raekwon:
    persist_state: true
    states:  
      right_orbit_1:
        label:
        #show_when_active:
        #  show_tokens:
        #    msg: Shoot Right Orbit to Raekwon Ramp
      side_ramp_1:
        label:
        #show_when_active:
        # show tokens:
        #    msg: Shoot Raekwon Ramp
      Center_ramp_1:
        label:
        #show_when_active:
        #  show_tokens:
        #    msg: Shoot Center Ramp to Side Ramp
      side_ramp_2:
        label:
        #show_when_active:
        #  show_tokens:
        #    msg: Shoot Raekwon Ramp
      right_orbit_2:
        label:
        #show_when_active:
        #  show_tokens:
        #    msg: Shoot Right Orbit to Raekwon Ramp
      side_ramp_3:
        label:
        #show_when_active:
        #  show_tokens:
        #   msg: Shoot Raekwon Ramp
      Center_ramp_2:
        label:
        #show_when_active:
        #  show_tokens:
        #    msg: Shoot Center Ramp to Side Ramp
      side_ramp_4:
        label:
       # show_when_active:
       #   show_tokens:
       #     msg: Shoot Raekwon Ramp
      right_orbit_3:
        label:
        #show_when_active:
         # show_tokens:
        #    msg: Shoot Right Orbit to Raekwon Ramp
      side_ramp_5:
        label:
       # show_when_active:
          #show_tokens:
         #   msg: Shoot Raekwon Ramp
      Center_ramp_3:
        label:
        #show_when_active:
          #show_tokens:
         #   msg: Shoot Center Ramp to Side Ramp
      side_ramp_6:
        label:
        #show_when_active:
       #  show_tokens:
       #     msg: Shoot Raekwon Ramp
      raekwon_completed:
    transitions:
      - events: step1
        source: right_orbit_1
        target: side_ramp_1
      - events: step2
        source: side_ramp_1
        target: Center_ramp_1
      - events: step3
        source: Center_ramp_1
        target: side_ramp_2
      - events: step4
        source: side_ramp_2
        target: right_orbit_2
      - events: step4
        source: right_orbit_2
        target: side_ramp_3
      - events: step5
        source: side_ramp_3
        target: Center_ramp_2
      - events: step6
        source: Center_ramp_2
        target: side_ramp_4
      - events: step7
        source: side_ramp_4
        target: right_orbit_3
      - events: step8
        source: right_orbit_3
        target: side_ramp_5
      - events: step9
        source: side_ramp_5
        target: Center_ramp_3
      - events: step10
        source: Center_ramp_3
        target: side_ramp_6
      - events: step11
        source: side_ramp_6
        target: raekwon_completed

variable_player:
  step1:
    score: 10000
  step2:
    score: 15000
  step3:
    score: 20000
  step4:
    score: 25000
  step5: 
    score: 35000
  step6:
    score: 50000
  step7:
    score: 100000
  step8:
    score: 125000
  step9:
    score: 150000
  step10:
    score: 175000
  step11:
    score: 200000
  raekwon_completed:
    score: 200000

sounds:
  icecream:
    volume: 0.5
    priority: 100 
