#config_version=5
mode: 
  start_events: masta_killa_selected
  stop_events: masta_killa_completed
  priority: 1000

shot_groups:
  captives:
    shots: shot_car_crash, shot_captive_ball

state_machines:
  masta_killa:
    persist_state:
    states:  
      lower_scoop_1:
        label: Lower Scoop Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Masta Killa Scoop
      captives_1:
        label: Captives Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Car or Captive Ball
      lower_scoop_2:
        label: Lower Scoop Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Masta Killa Scoop
      captives_2:
        label: Captives Lit
#        show_when_active:
#         show_tokens:
#           msg: Shoot Car or Captive Ball
      lower_scoop_3:
        label: Lower Scoop Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Masta Killa Scoop
      captives_3:
        label: Captives Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Car or Captive Ball
      lower_scoop_4:
        label: Lower Scoop Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Masta Killa Scoop
      captives_4:
        label: Captives Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Car or Captive Ball
      lower_scoop_5:
        label: Lower Scoop Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Masta Killa Scoop
      captives_5:
        label: Captives Lit
#        show_when_active:
#          show_tokens:
#            msg: Shoot Car or Captive Ball
      masta_killa_completed:
    transitions:
      - events: step1
        source: lower_scoop_1
        target: captives_1
      - events: step2
        source: captives_1
        target: lower_scoop_2
      - events: step3
        source: lower_scoop_2
        target: captives_2
      - events: step4
        source: captives_2
        target: lower_scoop_3
      - events: step4
        source: lower_scoop_3
        target: captives_3
      - events: step5
        source: captives_3
        target: lower_scoop_4
      - events: step6
        source: lower_scoop_4
        target: captives_4
      - events: step7
        source: captives_4
        target: lower_scoop_5
      - events: step8
        source: lower_scoop_5
        target: captives_5
      - events: step9
        source: captives_5
        target: masta_killa_completed

variable_player:
  step1:
    score: 10000
  step2:
    score: 15000
  step3:
    score: 20000
  step4:
    score: 25000
  step5: 
    score: 35000
  step6:
    score: 50000
  step7:
    score: 100000
  step8:
    score: 125000
  step9:
    score: 150000
  masta_killa_completed:
    score: 200000

sounds:
  oldman:
    volume: 0.5
    priority: 100 
