#config_version=5 

hardware:
  platform: smart_virtual

modes:
  - base
  - skill
  - carousel
  - qualify
  - tilt

switches:
  s_left_flipper:
    number: 1
    tags: left_flipper
  s_right_flipper:
    number: 9
    tags: right_flipper
  s_upper_flipper:
    number: 10
    tags: upper_flipper
  s_trough1:
    number: 2
    type: NC
  s_trough2:
    number: 3
    type: NC
  s_trough3:
    number: 4
    type: NC
  s_trough4:
    number: 5
    type: NC
  s_trough5:
    number: 6
    type: NC
  s_trough6:
    number: 7
    type: NC
  s_trough_jam:
    number: 8
    type: NC
  s_plunger_lane:
    number: 13
  s_launch_button:
    number: 14
  s_start:
    number: 11
    tags: start
  s_right_inlane:
    number: 12
  s_plumb_bob:
    number: 15
  s_left_outlane:
    number: 16
  s_left_inlane:
    number: 17
  s_slam_tilt:
    number: 18
  s_coin_door_closed:
    number: 19
  s_standup_1:
    number: 20
  s_standup_2:
    number: 21
  s_standup_3:
    number: 22
  s_standup_4:
    number: 23
  s_standup_5:
    number: 24
  s_left_slingshot:
    number: 25
  s_right_slingshot:
    number: 26
  s_upper_slingshot:
    number: 27
  s_left_jet_bumper:
    number: 28
  s_right_jet_bumper:
    number: 29
  s_right_ramp_enter:
    number: 30
  s_right_ramp_exit:
    number: 31
  s_left_ramp_enter:
    number: 32
  s_left_ramp_exit:
    number: 33
  s_side_ramp_enter: left_
    number: 34
  s_side_ramp_exit:
    number: 35
  s_center_ramp:
    number: 36
  s_right_spinner:
    number: 37
  s_left_loop:
    number: 38
  s_left_rollover:
    number: 39
  s_center_rollover:
    number: 40
  s_right_rollover:
    number: 41
  s_chase_car_1:
    number: 42
  s_chase_car_2:
    number: 43
  s_chase_car_standup:
    number: 44
  s_upper_rebound:
    number: 45
  s_top_popper:
    number: 46
  s_bottom_popper:
    number: 47
  s_lower_rebound:
    number: 48
  s_ring_ramp:
    number: 49
  s_captive_ball_standup:
    number: 50
  s_hive_exit_subway:
    number: 51
  s_hive_exit_pops:
    number: 52
  s_hive_exit_eject:
    number: 53
  s_hive_exit_left_inlane:
    number: 54
  s_left_saucer:
    number: 55
  s_right_loop:
    number: 56

coils:
  c_flipper_left_main:
    number:
    default_pulse_ms: 20
  c_flipper_left_hold:
    number:
    allow_enable: true
  c_flipper_right_main:
    number:
    default_pulse_ms: 20
  c_flipper_right_hold:
    number:
    allow_enable: true
  c_flipper_upper_main:
    number:
    default_pulse_ms: 20
  c_flipper_upper_hold:
    number:
    allow_enable: true
  c_trough_eject:
    number: 
    default_pulse_ms: 20
  c_plunger:
    number:
    default_pulse_ms: 20
  c_top_popper:
    number:
  c_bottom_popper:
    number:
  c_eject:
    number:
  c_diverter:
    number:
  c_left_slingshot:
    number:
  c_right_slingshot:
    number:
  c_upper_slingshot:
    number:
  c_left_jet_bumper:
    number:
  c_right_jet_bumper:
    number:
  c_left_saucer:
    number:
    
lights:
  rear_car_crash:
    number: 0
    type: grb
  middle_car_crash:
    number: 1
    type: grb
  front_car_crash:
    number: 2
    type: grb
  rza_r:
    number: 3
    type: grb
  rza_z:
    number: 4
    type: grb
  rza_a:
    number: 5
    type: grb
  between_pops:
    number: 6
    type: grb
  odb_arrow:
    number: 7
    type: grb
  odb_insert:
    number: 8
    type: grb
  mk_arrow:
    number: 9
    type: grb
  mk_insert:
    number: 10
    type: grb
  ugod_arrow:
    number: 11
    type: grb
  ugod_insert:
    number: 12
    type: grb
  extra_ball:
    number: 13
    type: grb
  raekwon_arrow:
    number: 14
    type: grb
  raekwon_insert:
    number: 15
    type: grb
  mm_arrow:
    number: 16
    type: grb
  mm_insert:
    number: 17
    type: grb
  deck_top:
    number: 18
    type: grb
  deck_bottom:
    number: 19
    type: grb
  gk_arrow:
    number: 20
    type: grb
  gk_insert:
    number: 21
    type: grb
  cream_c:
    number: 22
    type: grb
  cream_r:
    number: 23
    type: grb
  cream_e:
    number: 24
    type: grb
  cream_a:
    number: 25
    type: grb
  cream_m:
    number: 26
    type: grb
  captive_ball:
    number: 27
    type: grb
  shaolin:
    number: 28
    type: grb
  simple:
    number: 29
    type: grb
  nuthin: 
    number: 30
    type: grb
  triumph:
    number: 31
    type: grb
  gravel: 
    number: 32
    type: grb
  protect:
    number: 33
    type: grb
  cream_multi:
    number: 34
    type: grb
  left_inlane:
    number: 35
    type: grb
  right_inlane:
    number: 36
    type: grb
  left_ball_save:
    number: 37
    type: grb
  right_ball_save:
    number: 38
    type: grb
  shoot_again:
    number: 39
    type: grb
  gza_arrow:
    number: 40
    type: grb
  gza_insert:
    number: 41
    type: grb
    
playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
  upper_flipper:
    main_coil: c_flipper_upper_main
    hold_coil: c_flipper_upper_hold
    activation_switch: s_upper_flipper

displays:
  window:
    width: 800
    height: 600

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60

slide_player:
  init_done: welcome_slide

keyboard:
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_inlane
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  l:
    switch: s_launch_button
    toggle: true
  w:
    switch: s_left_outlane
  e:
    switch: s_left_inlane
  r:
    switch: s_right_outlane
  t:
    switch: s_plumb_bob
  y:
    switch: s_standup_1
  u:
    switch: s_standup_2
  i:
    switch: s_standup_3
  o:
    switch: s_standup_4
  p:
    switch: s_standup_5
  a:
    switch: s_left_slingshot
  d:
    switch: s_right_slingshot
  f:
    switch: s_upper_slingshot
  g:
    switch: s_left_jet_bumper
  h:
    switch: s_right_jet_bumper
  j:
    switch: s_right_ramp_enter
  k:
    switch: s_right_ramp_exit
  ';':
    switch: s_left_ramp_enter
  x:
    switch: s_left_ramp_exit
  c:
    switch: side_ramp_enter
  v:
    switch: side_ramp_exit
  b:
    switch: s_center_ramp
  ',':
    switch: s_right_spinner
  '.':
    switch: s_left_loop
  '`':
    switch: s_left_rollover
  6:
    switch: s_center_rollover
  7:
    switch: s_right_rollover
  8:
    switch: s_chase_car_1
  9:
    switch: s_upper_rebound
  0:
    switch: s_top_popper
  '-':
    switch: s_bottom_popper
  '=':
    switch: s_lower_rebound
  '[':
    switch: s_ring_ramp
  ']':
    switch: s_captive_ball_standup
  'n':
    switch: s_left_saucer

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: true
  bd_plunger:
    ball_switches: s_plunger_lane
    entrance_count_delay: 300ms
    eject_coil: c_plunger
    player_controlled_eject_event: s_launch_button_active
    eject_timeouts: 3s
  bd_lower_vuk:
    ball_switches: s_bottom_popper
    eject_coil: c_bottom_popper
    eject_timeouts: 2s
  bd_upper_vuk:
    ball_switches: s_top_popper
    eject_coil: c_top_popper
    eject_timeouts: 2s
  bd_left_saucer:
    ball_switches: s_left_saucer
    eject_coil: c_left_saucer
    eject_timeouts: 3s


virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  upper_slingshot:
    coil: c_upper_slingshot
    switch: s_upper_slingshot
  left_jet:
    coil: c_left_jet_bumper
    switch: s_left_jet_bumper
  right_jet:
    coil: c_right_jet_bumper
    switch: s_right_jet_bumper 

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_plunger_lane_ball_eject_success
    auto_launch: true
    balls_to_save: 1
    debug: true

sound_system:
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.5
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.7
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.4

assets:
  sounds:
    default:
      load: on_demand
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice

machine_vars:
  master_volume:
    initial_value: 0.25   # Set this to any value you want
    # value_type: floatfff
    persist: true         # If false, the volume will reset to default
                          # each time the machine boots up


