#config_version=5
mode:
  start_events: ball_started
  priority: 1000

counters:
  deck_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_deck_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_chase_car_1_hit
  ugod_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_ugod_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_top_popper_hit
  method_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_methodman_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_left_ramp_exit_hit
  odb_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_odb_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_center_ramp_hit
  mastakilla_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_mastakilla_start
    enable_events: enable_qualify
    events_when_hit: mkq_hit
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: shot_bottom_scoop_hit
  raekwon_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_raekwon_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_side_ramp_hit
  ghostface_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_ghostface_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_right_ramp_exit_hit
  gza_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_gza_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_right_loop_hit
  rza_qualify_counter:
    starting_count: 0
    count_complete_value: 3
    events_when_complete: mode_rza_start
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: rollover_complete
  cappadonna_qualify_counter:
    starting_count: 0
    count_complete_value: 20
    events_when_complete: cappadonna_qualified
    enable_events: enable_qualify
    disable_events: 
    start_enabled: true
    persist_state: true
    reset_on_complete: false
    restart_events: reset_qualify_modes
    count_events: s_captive_ball_standup_hit

variable_player:
  mastakilla_complete:
    mastakilla_qualified: 1
  deck_complete:
    deck_qualified: 1
  ugod_complete:
    ugod_qualified: 1
  method_complete:
    method_qualified: 1
  odb_complete:
    odb_qualified: 1
  raekwon_complete:
    raekwon_qualified: 1
  ghostface_complete:
    ghostface_qualified: 1
  gza_complete:
    gza_qualified: 1
  rza_complete:
    rza_qualified: 1

#playlists:
#  playlistdeckqual:
#    shuffle: false
#    repeat: false
#    sounds:
#      - deckqual1
#      - deckqual2
#      - deckqual3
#  playlistghostfacequal:
#    shuffle: false
#    repeat: false
#    sounds:
#      - ghostfacequal1
#      - ghostfacequal2
#      - ghostfacequal3
#  playlistmethodqual:
#    shuffle: false
#    repeat: false
#    sounds:
#      - methodqual1
#      - methodqual2
#      - methodqual2
#  playlistmkqual:
#    shuffle: false
#    repeat: false
#    sounds:
#      - mkqual1
#      - mkqual2
#      - mkqual2
#  playlistodbqual:
#    shuffle: false
#    repeat: false
#    sounds:
#      - odbqual1
#      - odbqual2
#      - odbqual3
#  playlistraekwonqual:
#    shuffle: false
#    repeat: false
#    sounds:
#      - raekwonqual1
#      - raekwonqual2
#      - raekwonqual2
#  playlistugodqual:
#    shuffle: false
#    repeat: false
#    sounds:
#      - ugodqual1
#      - ugodqual2
#      - ugodqual3
 
#playlist_player:
#  shot_bottom_scoop_hit:
#    playlist_track:
#      playlist: playlistmkqual
#      action: play
  #playlist_track_playlist_sound_stopped:
  #  playlist:
  #    action: advance

shows:
  play_qual_sound:
    - time: 0
      events:
        play_sound: {"sound": (sound_to_play), "volume": 0.7, "loops": 0}

#show_player:
  # MKqualifier
#  shot_bottom_scoop_hit{count==1}:
#    play_qual_sound:
#      show_tokens:
#        sound_to_play: mkqual1

#playlist_player:
#  s_chase_car_1_hit: playlistdeckqual
#  s_top_popper_hit: playlistugodqual
#  s_left_ramp_exit_hit: playlistmethodqual
#  s_center_ramp_hit: playlistodbqual
#  shot_bottom_scoop_hit: playlistmkqual
#  s_side_ramp_hit: playlistraekwonqual
#  rollover_complete: playlistrzaqual
#  s_right_ramp_exit_hit: playlistghostfacequal
#  gza_qualify_counter_complete: gzaqual3
  
slides:
  deck_qualified_slide:
    - type: image
      image: deckqualified
  ghostface_qualified_slide:
    - type: image
      image: ghostfacequalified
  gza_qualified_slide:
    - type: image
      image: gzaqualified
  mastakilla_qualified_slide:
    - type: image
      image: mastakillaqualified
  methodman_qualified_slide:
    - type: image
      image: methodmanqualified
  odb_qualified_slide:
    - type: image
      image: odbqualified
  raekwon_qualified_slide:
    - type: image
      image: raekwonqualified
  rza_qualified_slide:
    - type: image
      image: rzaqualified
  ugod_qualified_slide:
    - type: image
      image: ugodqualified
      
slide_player:
  deck_qualified:
    deck_qualified_slide:
      expire: 2s
  ghostface_qualified:
    ghostface_qualified_slide:
      expire: 2s
  gza_qualified:
    gza_qualified_slide:
      expire: 2s
  mastakilla_qualified:
    mastakilla_qualified_slide:
      expire: 2s
  methodman_qualified:
    methodman_qualified_slide:
      expire: 2s
  odb_qualified:
    odb_qualified_slide:
      expire: 2s
  raekwon_qualified:
    raekwon_qualified_slide:
      expire: 2s
  rza_qualified:
    rza_qualified_slide:
      expire: 2s
  ugod_qualified:
    ugod_qualified_slide:
      expire: 2s
