#config_version=5

mode:
  start_events: cream_started
  stop_events:
  priority: 1000
  
accruals:
  cream_accrual:
    events:
      -standup_1
      -standup_2
      -standup_3
      -standup_4
      -standup_5
    reset_on_complete: false
  event_player:
  test_event{device.accruals.test_accrual.value[0]}: standup_1
  test_event{device.accruals.test_accrual.value[1]}: standup_2
  test_event{device.accruals.test_accrual.value[2]}: standup_3
  test_event{device.accruals.test_accrual.value[3]}: standup_4
  test_event{device.accruals.test_accrual.value[4]}: standup_5
  test_event{device.accruals.test_accrual.completed}: cream_accrual_completed

multiballs:
  add_a_ball:
    ball_count: 1
    ball_count_type: add
    enable_events: cream_accrual_completed
    disable_events: cream_disable
    start_events: cream_start
    stop_events: cream_stop
    add_a_ball_events: cream_accrual_completed

sounds:
  cream:
    file: creamedit.wav
    volume: 0.5
    
sound_player:
  mode_cream_started:
    cream:
    
player_vars:
  multiplier:
    value_type: int
    initial_value: 2

